### ISSUE TITLE
URI.escaped removed in Ruby 3, deprecation warning in newer 2.7s

### ISSUE THREAD

**Issue by jtgorman** [UIUCLibrary/alma-api-batch#2]
Trigger by calling api.get 

home/centos/.rvm/gems/ruby-3.1.2/gems/alma_api-0.4.2/lib/alma_api/batch.rb:210:in `_uri': undefined method `escape' for URI:Module (NoMethodError)
                                                   
        URI( URI.escape( uri ) )                   
                ^^^^^^^                            
        from /home/centos/.rvm/gems/ruby-3.1.2/gems/alma_api-0.4.2/lib/alma_api/batch.rb:217:in `get'
        from (irb):5:in `<main>'                   
	from /home/centos/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /home/centos/.rvm/rubies/ruby-3.1.2/bin/irb:25:in `load'
	from /home/centos/.rvm/rubies/ruby-3.1.2/bin/irb:25:in `<main>'

**Comment by jtgorman** [comment]
Fixed
